### PR TITLE
fixed #3

### LINKED ISSUE #3: Segfault after allocating much memory in Worker task php 7.3+
If you have some task which allocates memory, Worker can crash with segfault in another task. Work only if you have more than one Worker. In production, I have the task which periodically gets from DB data around 300KB and after some hours Worker crashed in another task. I wrote the example of code which usually crashing with segfault in few seconds.

```
class AllocateMemoryTask extends \Threaded {

    public function run() {
        var_dump(get_class($this));
        $justAllocateManyData = [];
        for ($i = 0; $i < 100000; $i++) {
            $justAllocateManyData[] = 'test';
        }
        $serializeData = serialize($justAllocateManyData);
        $test = [];
        for ($i = 0; $i < 100; $i++) {
            $test[] = unserialize($serializeData);
        }        
    }

}

class SimpleTask extends \Threaded {

    public function run() {
        var_dump(get_class($this));
    }

}

class MyWorker extends \Worker {

    public function run() {
        ini_set("memory_limit", -1);
    }

    public function start(int $options = PTHREADS_INHERIT_CONSTANTS) {
        parent::start($options);
    }

}

$pool = new \Pool(4, MyWorker::class);

for ($i = 0; $i < 4; $i++) {
    $pool->submit(new AllocateMemoryTask());
}

while (true) {
    for ($i = 0; $i < 4; $i++) {
        $pool->submit(new SimpleTask());
    }
    sleep(1);
}
```

### PR DESCRIPTION
**Pull request by alleskos**
I fixed https://github.com/pmmp/pthreads/issues/3 But I didn't test it with version less than php 7.3

### CODE REVIEW

**Comment by dktapps** [comment]
I'm not sure I understand why this fixes the bug described, would you mind explaining?

**Comment by dktapps** [comment]
Judging by the code I've seen in opcache, there are specific circumstances where the memory should be allocated like this, depending on `ZEND_ACC_DONE_PASS_TWO`.

**Comment by alleskos** [comment]
About opcodes and literals change https://github.com/php/php-src/blob/PHP-7.3.14/UPGRADING.INTERNALS#L47-L63
Example of code wich work with memory for opcodes and literals
https://github.com/php/php-src/blob/cf9362195bdd790f5da1f5d37b336f900fdb022b/ext/opcache/Optimizer/zend_optimizer.c#L1074-L1087

**Comment by dktapps** [comment]
I don't think this fix is correct. The memory isn't expected to be allocated like this unless `ZEND_ACC_DONE_PASS_TWO` is set; it's explicitly removed here: https://github.com/pmmp/pthreads/pull/4/files#diff-ef0b26d0caa88af3a732194688d24af0R344

**Comment by dktapps** [comment]
I suspect this bug will not occur on 32-bit builds. I also suspect that this fix will break on 32-bit builds.

It would appear that 64-bit unconditionally uses this allocator behaviour. It's controlled by the `ZEND_USE_ABS_CONST_ADDR` flag.

References:
https://github.com/php/php-src/blob/cf9362195bdd790f5da1f5d37b336f900fdb022b/Zend/zend_opcode.c#L472-L475
https://github.com/php/php-src/blob/cf9362195bdd790f5da1f5d37b336f900fdb022b/Zend/zend_opcode.c#L900-L921

**Comment by dktapps** [comment]
Correction: 32-bit unconditionally uses separated blocks. 64-bit uses separated blocks when `ZEND_ACC_DONE_PASS_TWO` is not set.

**Comment by dktapps** [comment]
closed by 7a7bde07a88285c3c46b3f5ff8cf4df44c585058.

**Pull request closed without merging**
